apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: naturayur/order-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8004
          env:
            - name: PORT
              value: "8004"
            - name: NODE_ENV
              value: "production"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: order-connection-string
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt-secret
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: secret-key
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: webhook-secret
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: email-user
            - name: EMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: email-pass
            - name: EMAIL_SERVICE
              value: "gmail"
            - name: PRODUCT_SERVICE_URL
              value: "http://product-service:8003"
            - name: CART_SERVICE_URL
              value: "http://cart-service:8002"
            - name: USER_SERVICE_URL
              value: "http://auth-service:8001"
            - name: FRONTEND_URL
              value: "https://naturayur.com"
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
  type: ClusterIP
